#!/usr/bin/env bash

# File: 2-ssh_config

# Host directive for your server
Host root@3.80.33.136 
    # Use the private key
    IdentityFile ~/.ssh/school
    # Disable password authentication
    PasswordAuthentication no
